"""Add description

Revision ID: 0714a630f4ea
Revises: 354f5110a54d
Create Date: 2018-11-19 17:43:55.677221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0714a630f4ea'
down_revision = '354f5110a54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('exact_order_description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devis', 'exact_order_description')
    # ### end Alembic commands ###
