"""add tier table

Revision ID: 1324a64be45a
Revises: 
Create Date: 2018-10-23 18:43:47.561205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1324a64be45a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exact_id', sa.String(length=255), nullable=True),
    sa.Column('exact_account_code', sa.String(length=255), nullable=True),
    sa.Column('exact_name', sa.String(length=255), nullable=True),
    sa.Column('exact_is_supplier', sa.Boolean(), nullable=True),
    sa.Column('exact_is_reseller', sa.Boolean(), nullable=True),
    sa.Column('exact_is_sales', sa.Boolean(), nullable=True),
    sa.Column('exact_is_purchase', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tier')
    # ### end Alembic commands ###
