"""add models for planning

Revision ID: 2d70339316e6
Revises: 9e8a6ceb7589
Create Date: 2021-05-22 17:33:57.898178

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2d70339316e6"
down_revision = "9e8a6ceb7589"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exact_id", sa.String(length=255), nullable=True),
        sa.Column("exact_code", sa.String(length=255), nullable=True),
        sa.Column("exact_description", sa.String(length=255), nullable=True),
        sa.Column("exact_modified", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exact_id"),
    )
    op.create_table(
        "gamme",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exact_item_id", sa.String(length=255), nullable=True),
        sa.Column("exact_value", sa.String(length=255), nullable=True),
        sa.Column("exact_modified", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exact_item_id"],
            ["article.exact_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ligne_de_commande",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exact_order_id", sa.String(length=255), nullable=True),
        sa.Column("exact_id", sa.String(length=255), nullable=True),
        sa.Column("exact_item_id", sa.String(length=255), nullable=True),
        sa.Column("exact_line_number", sa.Integer(), nullable=True),
        sa.Column("exact_item_description", sa.String(length=255), nullable=True),
        sa.Column("exact_amount", sa.Numeric(precision=20, scale=3), nullable=True),
        sa.Column("exact_modified", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exact_item_id"],
            ["article.exact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["exact_order_id"],
            ["commande.exact_order_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exact_id"),
    )
    op.add_column(
        "commande",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.add_column(
        "commande",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.add_column(
        "devis",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.add_column(
        "devis",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.add_column(
        "tier",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.add_column(
        "tier",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.add_column(
        "tier_client",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.add_column(
        "tier_client",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.add_column(
        "tier_supplier",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.add_column(
        "tier_supplier",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tier_supplier", "updated_at")
    op.drop_column("tier_supplier", "created_at")
    op.drop_column("tier_client", "updated_at")
    op.drop_column("tier_client", "created_at")
    op.drop_column("tier", "updated_at")
    op.drop_column("tier", "created_at")
    op.drop_column("devis", "updated_at")
    op.drop_column("devis", "created_at")
    op.drop_column("commande", "updated_at")
    op.drop_column("commande", "created_at")
    op.drop_table("ligne_de_commande")
    op.drop_table("gamme")
    op.drop_table("article")
    # ### end Alembic commands ###
