"""add last sync success

Revision ID: 7c9e0b2dd743
Revises: 2d70339316e6
Create Date: 2021-05-25 09:50:19.344051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9e0b2dd743'
down_revision = '2d70339316e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_sync_success',
    sa.Column('sync_type', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('sync_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_sync_success')
    # ### end Alembic commands ###
