"""add devis table

Revision ID: 98f4927abc23
Revises: 1324a64be45a
Create Date: 2018-10-23 19:00:06.815876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f4927abc23'
down_revision = '1324a64be45a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exact_quotation_id', sa.String(length=255), nullable=True),
    sa.Column('exact_quotation_number', sa.Integer(), nullable=True),
    sa.Column('exact_tier_id', sa.String(length=255), nullable=True),
    sa.Column('exact_your_ref', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['exact_tier_id'], ['tier.exact_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exact_quotation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devis')
    # ### end Alembic commands ###
