"""Add order status

Revision ID: 9e8a6ceb7589
Revises: bcbf3b0d429f
Create Date: 2020-02-10 16:14:05.857650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8a6ceb7589'
down_revision = 'bcbf3b0d429f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commande', sa.Column('exact_status', sa.Integer(), nullable=True))
    op.add_column('commande', sa.Column('exact_status_description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commande', 'exact_status_description')
    op.drop_column('commande', 'exact_status')
    # ### end Alembic commands ###
