"""Add tier_client and tier_supplier

Revision ID: bcbf3b0d429f
Revises: d2dc2d735eab
Create Date: 2019-02-10 18:16:19.137100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbf3b0d429f'
down_revision = 'd2dc2d735eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exact_id', sa.String(length=255), nullable=True),
    sa.Column('prefixed_account_code', sa.String(length=255), nullable=True),
    sa.Column('exact_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exact_id')
    )
    op.create_table('tier_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exact_id', sa.String(length=255), nullable=True),
    sa.Column('prefixed_account_code', sa.String(length=255), nullable=True),
    sa.Column('exact_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tier_supplier')
    op.drop_table('tier_client')
    # ### end Alembic commands ###
