"""missing_field

Revision ID: c28d2df0e6ca
Revises: 7c9e0b2dd743
Create Date: 2021-06-18 10:29:26.107365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28d2df0e6ca'
down_revision = '7c9e0b2dd743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commande', sa.Column('exact_amount', sa.Numeric(precision=20, scale=3), nullable=True))
    op.add_column('commande', sa.Column('exact_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commande', 'exact_modified')
    op.drop_column('commande', 'exact_amount')
    # ### end Alembic commands ###
