"""Add order number

Revision ID: d2dc2d735eab
Revises: 0714a630f4ea
Create Date: 2018-11-27 14:41:05.344057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2dc2d735eab'
down_revision = '0714a630f4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commande', sa.Column('exact_order_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commande', 'exact_order_number')
    # ### end Alembic commands ###
