# Generated by Django 3.2.7 on 2021-09-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlembicVersion',
            fields=[
                ('version_num', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alembic_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('exact_code', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_description', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_modified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_order_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('exact_order_description', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_your_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_order_number', models.IntegerField(blank=True, null=True)),
                ('exact_status', models.IntegerField(blank=True, null=True)),
                ('exact_status_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('exact_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('exact_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commande',
            },
        ),
        migrations.CreateModel(
            name='LastSyncSuccess',
            fields=[
                ('sync_type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'last_sync_success',
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('exact_account_code', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_is_supplier', models.IntegerField(blank=True, null=True)),
                ('exact_is_reseller', models.IntegerField(blank=True, null=True)),
                ('exact_is_sales', models.IntegerField(blank=True, null=True)),
                ('exact_is_purchase', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tier',
            },
        ),
        migrations.CreateModel(
            name='TierClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('prefixed_account_code', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tier_client',
            },
        ),
        migrations.CreateModel(
            name='TierSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('prefixed_account_code', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tier_supplier',
            },
        ),
        migrations.CreateModel(
            name='LigneDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('exact_line_number', models.IntegerField(blank=True, null=True)),
                ('exact_item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('exact_modified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('schedule_priority', models.IntegerField()),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('exact_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.article')),
                ('exact_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.commande')),
            ],
            options={
                'db_table': 'ligne_de_commande',
            },
        ),
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_value', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_modified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('exact_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.article')),
            ],
            options={
                'db_table': 'gamme',
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_quotation_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('exact_quotation_number', models.IntegerField(blank=True, null=True)),
                ('exact_your_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_order_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('exact_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tier')),
            ],
            options={
                'db_table': 'devis',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='exact_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tier'),
        ),
    ]
