# Generated by Django 3.2.7 on 2021-09-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20210907_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='exact_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tier', to_field='exact_id'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='exact_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tier', to_field='exact_id'),
        ),
        migrations.AlterField(
            model_name='gamme',
            name='exact_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.article', to_field='exact_id'),
        ),
    ]
