# Generated by Django 3.2.7 on 2021-09-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20210907_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedecommande',
            name='exact_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.article', to_field='exact_id'),
        ),
        migrations.AlterField(
            model_name='lignedecommande',
            name='exact_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.commande', to_field='exact_order_id'),
        ),
        migrations.AlterField(
            model_name='lignedecommande',
            name='schedule_priority',
            field=models.IntegerField(default=1),
        ),
    ]
