# Generated by Django 3.2.7 on 2021-10-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0006_auto_20211013_1702"),
    ]

    operations = []
