# Generated by Django 3.2.7 on 2021-10-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_alter_lignedecommande_gamme_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedecommande',
            name='gamme_status',
            field=models.TextField(blank=True),
        ),
    ]
