# Generated by Django 3.2.7 on 2021-10-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_auto_20211013_1732'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lignedecommande',
            table='ligne_de_commande',
        ),
    ]
