# Generated by Django 3.2.7 on 2021-10-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_alter_lignedecommande_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('hex_color', models.CharField(max_length=7)),
            ],
        ),
    ]
