# Generated by Django 3.2.8 on 2021-10-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecommande',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lignedecommande',
            name='parts_status',
            field=models.CharField(choices=[('sur_place', 'Sur Place'), ('partiel', 'Partiel'), ('non_dispo', 'Non Dispo')], default='non_dispo', max_length=10),
        ),
    ]
