# Generated by Django 3.2.8 on 2021-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_auto_20211021_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='hex_color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
