# Generated by Django 3.2.8 on 2021-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_tier_hex_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedecommande',
            name='exact_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
