# Generated by Django 3.2.8 on 2021-11-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_lignedecommande_exact_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedecommande',
            name='exact_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
